name: "DEV DEPLOY"

on:
  push:
    branches:
      - developer

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      action: ${{ github.event.head_commit.message }}  # Usa a mensagem do commit
      aws-assume-role-arn: "arn:aws:iam::905418073202:role/GitAction-DiegoNorman-pipiline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "norman-tfvars"
      aws-lock-dynamodb-table: "diegonorman-us-east-1-terraform-lock"
    if: contains(github.event.head_commit.message, 'destroy')  # Condição para executar destroy
