name: "DEV DEPLOYMENT"

on:
    push:
        branches:
          - developer

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
          environment: dev
          aws-assume-role-arn: "arn:aws:iam::905418073202:role/GitAction-DiegoNorman-pipiline"
          aws-region: "us-east-1"
          aws-statefile-s3-bucket: "norman-tfvars"
          aws-lock-dynamodb-table: "diegonorman-us-east-1-terraform-lock"
